name: keeeper85

services:
  eureka:
    build: ./eureka-discovery
#    image: keeeper85/eureka
    ports:
      - "8761:8761"
    networks:
      - backend

  gaminatorium:
    build: ./gaminatorium-main
#    image: keeeper85/gaminatorium
    ports:
      - "8080:8080"
      - "[::]:80:8080"
    networks:
      - backend
    depends_on:
      - eureka
      - gaminatorium-postgres
    environment:
      EUREKA_URI: http://eureka:8761/eureka

  gaminatorium-postgres:
    image: postgres:16.3
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak-gaminatorium:
    build: ./keycloak-config
    environment:
        EUREKA_URI: http://eureka:8761/eureka
        KC_DB_URL: jdbc:postgresql://gaminatorium-postgres:5432/${POSTGRES_DB}
        KC_DB_USERNAME: ${POSTGRES_USER}
        KC_DB_PASSWORD: ${POSTGRES_PASS}
        KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
        KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
    command:
      - start-dev
    depends_on:
      - eureka
      - gaminatorium-postgres
    ports:
      - "9090:8080"
    networks:
      - backend

  gateway:
    build: ./gateway-balancer
    #    image: keeeper85/gateway
    ports:
      - "9000:9000"
    networks:
      - backend
    depends_on:
      - gaminatorium
      - eureka
    environment:
      EUREKA_URI: http://eureka:8761/eureka

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
